# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '16'

      - name: Change .env.example to .env
        run: cd public && cp .env.example .env

      - name: Install dependencies frontend
        run: cd public && npm install

      # - name: Run tests frontend
      #   run: cd public && npm test

      - name: Get Github commit short SHA
        id: vars
        run: echo "COMMIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build frontend
        run: cd public && docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:${{ env.COMMIT_SHA }} -f ./Dockerfile .

      - name: Push frontend image to Docker Hub
        run: cd public && docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:${{ env.COMMIT_SHA }}

      - name: Finish frontend job
        run: echo "Frontend build and push completed."