# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'public/**'
      - 'server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'public/**'
      - 'server/**'

jobs:
  detect-changes:
    runs-on: self-hosted
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend:  ${{ steps.filter.outputs.backend }}
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'public/**'
            backend:
              - 'server/**'

      - name: Create short SHA
        id: sha
        run: echo "sha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

  build-and-test-frontend:
    runs-on: self-hosted
    needs: detect-changes
    # if: needs.detect-changes.outputs.frontend == 'true'
    env:
      COMMIT_SHA: ${{ needs.detect-changes.outputs.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: public/package-lock.json

      - name: Change .env.example to .env
        working-directory: ./public
        run: cp .env.example .env

      - name: Install dependencies frontend
        working-directory: ./public
        run: npm install

      # - name: Run tests frontend
      #   working-directory: ./public
      #   run: npm test -- --watchAll=false --passWithNoTests

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Build frontend
        working-directory: ./public
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:${{ env.COMMIT_SHA }} -f ./Dockerfile .

      - name: Push frontend image to Docker Hub
        working-directory: ./public
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:${{ env.COMMIT_SHA }}
      - name: Finish frontend job
        run: echo "Frontend build and push completed."

  build-and-test-backend:
    runs-on: self-hosted
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    env:
      COMMIT_SHA: ${{ needs.detect-changes.outputs.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Change .env.example to .env
        working-directory: ./server
        run: cp .env.example .env

      - name: Install dependencies backend
        working-directory: ./server
        run: npm install

      # - name: Run tests backend
      #   working-directory: ./server
      #   run: npm test

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Build backend
        working-directory: ./server
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-backend:${{ env.COMMIT_SHA }} -f ./Dockerfile . 
        
      - name: Push backend image to Docker Hub
        working-directory: ./server
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-backend:${{ env.COMMIT_SHA }}
      - name: Finish backend job
        run: echo "Backend build and push completed."

  deploy-frontend:
    runs-on: self-hosted
    needs: [build-and-test-frontend, detect-changes]
    environment:
      name: production
    # if: needs.detect-changes.outputs.frontend == 'true'
    env:
      COMMIT_SHA: ${{ needs.detect-changes.outputs.sha }}

    steps:
      - name: Get Git short SHA
        run: echo "COMMIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
        
      - name: Stop old container if exists
        run: |
          if [ "$(docker ps -q -f name=chat-app-frontend)" ]; then
            docker stop chat-app-frontend
            docker rm chat-app-frontend
          fi

      - name: Pull new image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:${{ env.COMMIT_SHA }}

      - name: Run new frontend container
        run: |
          docker run -d \
            --name chat-app-frontend \
            -p 9080:80 \
            ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:${{ env.COMMIT_SHA }}

      - name: Show frontend URL
        run: |
          IP=$(hostname -I | awk '{print $1}')
          echo "Frontend deployed on http://$IP:9080"
    
